version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: terms-logger-backend
    ports:
      - "8080:8080"
    volumes:
      # Пробрасываем код бэкенда для удобства локальной разработки
      - ./backend:/usr/src/app
      # Изолируем node_modules внутри контейнера, чтобы они не конфликтовали с локальными
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
